"""
Domain enums.

All business enums are defined here to ensure consistency across the system.
No hardcoded strings for business logic - use these enums.
"""
from enum import Enum


class CallType(str, Enum):
    """Type of call."""
    CSR_CALL = "csr_call"  # Customer service representative call
    SALES_CALL = "sales_call"  # Sales call
    MISSED_CALL = "missed_call"  # Missed call


class LeadStatus(str, Enum):
    """Lead status in the sales pipeline."""
    NEW = "new"
    WARM = "warm"
    HOT = "hot"
    QUALIFIED_BOOKED = "qualified_booked"
    QUALIFIED_UNBOOKED = "qualified_unbooked"
    QUALIFIED_SERVICE_NOT_OFFERED = "qualified_service_not_offered"
    NURTURING = "nurturing"
    DORMANT = "dormant"
    ABANDONED = "abandoned"
    CLOSED_WON = "closed_won"
    CLOSED_LOST = "closed_lost"


class DealStatus(str, Enum):
    """Deal status (operational stage)."""
    NEW = "new"
    NURTURING = "nurturing"
    BOOKED = "booked"
    NO_SHOW = "no_show"
    RESCHEDULED = "rescheduled"
    IN_PROGRESS = "in_progress"
    WON = "won"
    LOST = "lost"


class PipelineStage(str, Enum):
    """Pipeline stage - tracks where the lead is in the sales pipeline."""
    QUALIFIED = "qualified"
    UNQUALIFIED = "unqualified"
    SERVICE_NOT_OFFERED = "service_not_offered"
    BOOKED = "booked"
    APPOINTMENT = "appointment"
    APPOINTMENT_RAN = "appointment_ran"
    WON = "won"
    LOST = "lost"
    REVIEW = "review"


PIPELINE_STAGE_ORDER: dict[str, int] = {
    PipelineStage.UNQUALIFIED.value: 0,
    PipelineStage.SERVICE_NOT_OFFERED.value: 0,
    PipelineStage.REVIEW.value: 0,
    PipelineStage.QUALIFIED.value: 1,
    PipelineStage.BOOKED.value: 2,
    PipelineStage.APPOINTMENT.value: 3,
    PipelineStage.APPOINTMENT_RAN.value: 4,
    PipelineStage.WON.value: 5,
    PipelineStage.LOST.value: 5,
}


class AppointmentOutcome(str, Enum):
    """Appointment outcome."""
    PENDING = "pending"
    WON = "won"
    LOST = "lost"
    NO_SHOW = "no_show"
    RESCHEDULED = "rescheduled"


class ObjectionType(str, Enum):
    """Type of objection raised."""
    IMMEDIATE_SERVICE_UNAVAILABILITY = "immediate_service_unavailability"
    PHONE_CONNECTION_ISSUES = "phone_connection_issues"
    CUSTOMER_NEEDS_TIME_TO_DECIDE = "customer_needs_time_to_decide"
    SCHEDULING_CONFLICTS = "scheduling_conflicts"
    SERVICE_FEE_CONCERNS = "service_fee_concerns"
    IN_PERSON_ESTIMATES_ONLY = "in_person_estimates_only"
    INEFFICIENT_AGENT_COMMUNICATION = "inefficient_agent_communication"
    CUSTOMER_DATA_PRIVACY_CONCERNS = "customer_data_privacy_concerns"
    SERVICE_NOT_CATERED = "service_not_catered"
    OTHER = "other"


class SOPStage(str, Enum):
    """SOP (Standard Operating Procedure) stages."""
    GREETING = "greeting"
    QUALIFICATION = "qualification"
    PRESENTATION = "presentation"
    OBJECTION_HANDLING = "objection_handling"
    CLOSE = "close"
    FOLLOW_UP = "follow_up"


class TaskStatus(str, Enum):
    """Task status."""
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class TaskSource(str, Enum):
    """Source of task."""
    SHUNYA = "shunya"  # Generated by AI analysis
    MANUAL = "manual"  # Created manually
    SYSTEM = "system"  # System-generated


class UserRole(str, Enum):
    """User roles."""
    CSR = "csr"  # Customer Service Representative
    SALES_REP = "sales_rep"  # Sales Representative
    EXECUTIVE = "executive"  # Executive/Admin


class Stage(str, Enum):
    """
    Business stages for stage-based authorization.

    Stages represent where a lead/deal is in the pipeline.
    Authorization is based on stage, not hardcoded roles.
    """
    INBOUND = "inbound"  # New inbound lead
    QUALIFICATION = "qualification"  # Being qualified
    BOOKED = "booked"  # Appointment booked
    IN_PROGRESS = "in_progress"  # Deal in progress
    CLOSED = "closed"  # Deal closed (won/lost)


class AnalysisStatus(str, Enum):
    """Status of AI analysis job."""
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class CallStatus(str, Enum):
    """Status of call processing."""
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class VectorDBProvider(str, Enum):
    """Vector database provider."""
    PINECONE = "pinecone"
    WEAVIATE = "weaviate"
    PGVECTOR = "pgvector"


class InvitationStatus(str, Enum):
    """Invitation status."""
    PENDING = "pending"
    ACCEPTED = "accepted"
    EXPIRED = "expired"


class PendingActionStatus(str, Enum):
    """Pending action status."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    CONVERTED = "converted"


class LeaderboardPeriod(str, Enum):
    """Leaderboard period."""
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    QUARTERLY = "quarterly"
    YEARLY = "yearly"


class ProxySessionStatus(str, Enum):
    """Proxy session status for masked communications."""
    ACTIVE = "active"
    CLOSED = "closed"


class ProxySessionClosedReason(str, Enum):
    """Reason a proxy session was closed."""
    DEAL_WON = "deal_won"
    DEAL_LOST = "deal_lost"
    MANUAL = "manual"
    EXPIRED = "expired"


class MaskedCommType(str, Enum):
    """Type of masked communication."""
    SMS = "sms"
    CALL = "call"
    RECORDING = "recording"


class MaskedCommDirection(str, Enum):
    """Direction of masked communication."""
    HOMEOWNER_TO_REP = "homeowner_to_rep"
    REP_TO_HOMEOWNER = "rep_to_homeowner"